id: I17999B55
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3879final
source_file: null
initial_creation_type: input
imported: '2022-08-01T10:53:23.548747'
last_modified: '2022-08-01T10:53:23.548758'
parser: null
source_metadata:
  title: Commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
